services:
  postgres:
    image: postgres:14
    container_name: products-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - ./deployments/init-db:/docker-entrypoint-initdb.d

  api:
    build: .
    container_name: products-api
    ports:
      - "8080:8080"
    env_file:
    - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/products?sslmode=disable
    depends_on:
      - postgres
    restart: on-failure